spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proxybank
    username: root
   
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
proxybank:
  admin:
    username: admin1
    password: adminpwd
  security:
    token:
      secret: AjoutDuSelDeGuerande
